### ISSUE TITLE
Add day count

### ISSUE THREAD

**Issue by derflahax** [ThaCheeseBun/brb-rs#1]
Sorry for bad engles. Pls add days counter, i was asleep a few days 🛌🛌🛏💤and it said 107 hours😨😨😱 and not 4 days and some hours and stuff🧐😩 and everyone roasted🔥🔥 me so hard for not havin' days sorted on my brb counter🥺🥺😭😭🌊🌊🌊🌊
Otherwise its definetöy solid top 12 programs in my hard drive👩‍💻👨‍💻🖨, but please add mor folders so it fills up my doenload folder💥💥 after unzipping so i look hakcer😎😎

**Comment by ThaCheeseBun** [comment]
Thanks for poanting out issu 👍👍👍I not had program on for days so i no saw this happen 🤦‍♂️🤦‍♂️🤷‍♀️i will fix this right NOW ⛈⛈

**Comment by derflahax** [comment]
tank
